In [1]:
import numpy as np

In [59]:
X = np.array([[0,1,0,1],
              [1,0,1,1],
              [1,0,0,1],
              [1,0,1,0]])

y = np.array([0,0,1,1]) # this represents 4 rows of X. This count must be = to no. of rows in X

In [62]:
X[[False, False, True, True]] # Prints 3rd and 4th rows from X
X[[True, False, True, False]] # Prints 1st and 3rd rows from X

array([[0, 1, 0, 1],
       [1, 0, 0, 1]])

In [63]:
counts = {}

for label in np.unique(y): # label will be 0 and 1
#    print(label)
#    print(y==label)
#    print(X[y==label])
    counts[label] = X[y == label].sum(axis=0) # axis=0 means sum by column
    print(counts[label])

print('Feature counts:\n{}'.format(counts))

[1 1 1 2]
[2 0 1 1]
Feature counts:
{0: array([1, 1, 1, 2]), 1: array([2, 0, 1, 1])}


In [46]:
a = np.arange(12)**2                       # the first 12 square numbers
i = np.array( [ 1,1,3,8,5 ] )              # an array of indices
print(a[i])                                # the elements of a at the positions i


j = np.array( [ [ 3, 4], [ 9, 7 ] ] )      # a bidimensional array of indices
print(a[j])                                # the same shape as j

[ 1  1  9 64 25]
[[ 9 16]
 [81 49]]


In [47]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [48]:
b = a>4
a[b] # same as a[a>4]

array([ 5,  6,  7,  8,  9, 10, 11])

In [38]:
a[b] = 0 # All elements of 'a' higher than 4 become 0
a

array([[0, 1, 2, 3],
       [4, 0, 0, 0],
       [0, 0, 0, 0]])