# NumPy Arrays

In [6]:
import numpy as np

In [7]:
np.array([1,2.5,4])

array([1. , 2.5, 4. ])

In [8]:
np.array([3,9,55])

array([ 3,  9, 55])

In [11]:
np.array([True, 'blah', 45])

array(['True', 'blah', '45'], dtype='<U5')

In [12]:
np.ones(7)

array([1., 1., 1., 1., 1., 1., 1.])

In [13]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [14]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [15]:
np.arange(4,18) # 4 inclusive, 18 exclusive

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17])

In [16]:
np.arange(4,18,3) # step by 3

array([ 4,  7, 10, 13, 16])

In [17]:
np.linspace(4,15,2) 
# It provides linearly spaced numberss from 4 to 15. 3rd param is the number of elements we want.

array([ 4., 15.])

In [18]:
np.linspace(4,15,3)

array([ 4. ,  9.5, 15. ])

In [19]:
np.linspace(0,100,13)

array([  0.        ,   8.33333333,  16.66666667,  25.        ,
        33.33333333,  41.66666667,  50.        ,  58.33333333,
        66.66666667,  75.        ,  83.33333333,  91.66666667,
       100.        ])

In [21]:
lins = np.linspace(5,15) # by default, it gives 50 elements
len(lins)
print(lins)

[ 5.          5.20408163  5.40816327  5.6122449   5.81632653  6.02040816
  6.2244898   6.42857143  6.63265306  6.83673469  7.04081633  7.24489796
  7.44897959  7.65306122  7.85714286  8.06122449  8.26530612  8.46938776
  8.67346939  8.87755102  9.08163265  9.28571429  9.48979592  9.69387755
  9.89795918 10.10204082 10.30612245 10.51020408 10.71428571 10.91836735
 11.12244898 11.32653061 11.53061224 11.73469388 11.93877551 12.14285714
 12.34693878 12.55102041 12.75510204 12.95918367 13.16326531 13.36734694
 13.57142857 13.7755102  13.97959184 14.18367347 14.3877551  14.59183673
 14.79591837 15.        ]


## Array operations

In [23]:
x_array = np.linspace(-1, 1, 9)
print(x_array)

[-1.   -0.75 -0.5  -0.25  0.    0.25  0.5   0.75  1.  ]


In [24]:
y_array = x_array**2 # can also be done by x_array * x_array
print(y_array)

[1.     0.5625 0.25   0.0625 0.     0.0625 0.25   0.5625 1.    ]


In [25]:
z_array = np.sqrt(y_array)
print(z_array)

[1.   0.75 0.5  0.25 0.   0.25 0.5  0.75 1.  ]


In [27]:
sum_array = x_array + y_array # elementwise addition
print(sum_array)

[ 0.     -0.1875 -0.25   -0.1875  0.      0.3125  0.75    1.3125  2.    ]


In [28]:
mult_array = x_array * y_array # elementwise multiplication.
print(mult_array)

[-1.       -0.421875 -0.125    -0.015625  0.        0.015625  0.125
  0.421875  1.      ]


In [29]:
div_array = x_array / y_array  #  division can be possible but be careful of division by zero
print(div_array)

[-1.         -1.33333333 -2.         -4.                 nan  4.
  2.          1.33333333  1.        ]


In [30]:
np.array([[1,2.0],[0,0],(1+1j,3.)])


array([[1.+0.j, 2.+0.j],
       [0.+0.j, 0.+0.j],
       [1.+1.j, 3.+0.j]])

In [31]:
np.arange(2, 10, dtype=float)

array([2., 3., 4., 5., 6., 7., 8., 9.])

In [33]:
np.array(3, 3, dtype=bool)

TypeError: Argument given by name ('dtype') and position (2)