In [1]:
import numpy as np

In [2]:
print(np.__version__)

1.15.1


In [3]:
import sys
print(sys.version)
print(sys.version_info)

3.6.3 |Anaconda, Inc.| (default, Nov  9 2017, 00:19:18) 
[GCC 7.2.0]
sys.version_info(major=3, minor=6, micro=3, releaselevel='final', serial=0)


In [7]:
an_array = np.arange(10)
print(an_array)

[0 1 2 3 4 5 6 7 8 9]


In [11]:
bool_array = np.full((3,3),True, dtype=bool)
print(bool_array)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [12]:
odd_array = an_array[an_array%2==1]
print(an_array)
print(odd_array)

[0 1 2 3 4 5 6 7 8 9]
[1 3 5 7 9]
